name: Deploy

on:
  push:
    branches:
      - stage
      - dev
  pull_request:
    types: [closed]
    branches:
      - main
      - stage
      - dev

jobs:
  deploy-dev:
    name: "Development"
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev')
    uses: ./.github/workflows/deployment.yml
    with:
      deployment_environment: dev

  deploy-stage:
    name: "Staging"
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/stage') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'stage')
    uses: ./.github/workflows/deployment.yml
    with:
      deployment_environment: stage

  deploy-prod:
    name: "Production"
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deployment.yml
    with:
      deployment_environment: prod